name = "supaflare-worker"
main = 'index.js'
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-10-10"
kv_namespaces = [
  { binding = "SUPAFLARE", id = "4256e26ed6780409cfad1e8e36d0c618", preview_id = "4256e26ed6780409cfad1e8e36d0c618" },
]
